/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FriendResult = IDL.Variant({
  'alreadyFriends' : IDL.Null,
  'sent' : IDL.Null,
  'alreadyRequested' : IDL.Null,
  'notFound' : IDL.Null,
  'selfRequest' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
  'alreadyAccepted' : IDL.Null,
  'removed' : IDL.Null,
});
export const RewardResult = IDL.Variant({
  'sent' : IDL.Null,
  'notFound' : IDL.Null,
  'notAdmin' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ModuleBanResult = IDL.Variant({
  'banned' : IDL.Null,
  'unbanned' : IDL.Null,
  'notBanned' : IDL.Null,
  'alreadyBanned' : IDL.Null,
});
export const ClaimResult = IDL.Variant({
  'claimed' : IDL.Null,
  'alreadyClaimed' : IDL.Record({ 'admin' : IDL.Principal }),
});
export const SpinWheelResult = IDL.Record({
  'remainingCooldown' : IDL.Nat,
  'pointsAdded' : IDL.Nat,
  'message' : IDL.Text,
});
export const ModuleStatus = IDL.Record({
  'moduleId' : IDL.Text,
  'banned' : IDL.Bool,
});
export const AvatarConfigRef = IDL.Record({
  'body' : IDL.Text,
  'hair' : IDL.Text,
  'head' : IDL.Text,
  'headwear' : IDL.Text,
  'shoes' : IDL.Text,
  'pants' : IDL.Text,
});
export const AdminUserView = IDL.Record({
  'status' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'lastSeen' : IDL.Int,
  'avatarConfig' : IDL.Opt(AvatarConfigRef),
});
export const Reward = IDL.Record({
  'userId' : IDL.Principal,
  'badges' : IDL.Vec(IDL.Text),
  'achievements' : IDL.Vec(IDL.Text),
  'totalTrophies' : IDL.Nat,
  'virtualPetLevel' : IDL.Nat,
  'points' : IDL.Nat,
});
export const AvatarConfig = IDL.Record({
  'body' : IDL.Text,
  'hair' : IDL.Text,
  'head' : IDL.Text,
  'headwear' : IDL.Text,
  'shoes' : IDL.Text,
  'pants' : IDL.Text,
});
export const AccessibilitySettings = IDL.Record({
  'highContrastMode' : IDL.Bool,
  'largeText' : IDL.Bool,
  'readAloudEnabled' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'mascotPreference' : IDL.Text,
  'theme' : IDL.Text,
  'approvedContacts' : IDL.Vec(IDL.Principal),
  'parentPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'screenTimeLimit' : IDL.Nat,
  'avatarUrl' : IDL.Text,
  'contentFilterLevel' : IDL.Text,
  'avatarConfig' : IDL.Opt(AvatarConfig),
  'accessibilitySettings' : AccessibilitySettings,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'threadId' : IDL.Text,
});
export const ChatThread = IDL.Record({
  'lastMessageAt' : IDL.Int,
  'name' : IDL.Text,
  'lastMessage' : IDL.Text,
  'friend' : IDL.Principal,
});
export const FriendRequest = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Principal,
  'createdAt' : IDL.Int,
});
export const Friend = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'online' : IDL.Bool,
});
export const ActivityEvent = IDL.Record({
  'principal' : IDL.Principal,
  'metadata' : IDL.Text,
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
});
export const SpinReward = IDL.Record({
  'value' : IDL.Text,
  'rewardType' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const VirtualPetHub = IDL.Record({
  'growthStage' : IDL.Nat,
  'accessories' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'warnedAboutExtremeChanges' : IDL.Bool,
  'happinessLevel' : IDL.Nat,
  'petName' : IDL.Text,
  'trophies' : IDL.Nat,
  'homeStyle' : IDL.Text,
  'decorations' : IDL.Vec(IDL.Text),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const ResetResult = IDL.Variant({
  'reset' : IDL.Null,
  'noAdmin' : IDL.Null,
});
export const ChatResult = IDL.Variant({
  'sent' : IDL.Null,
  'banned' : IDL.Null,
  'notFriends' : IDL.Null,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [FriendResult], []),
  'adminSendReward' : IDL.Func([IDL.Principal, IDL.Nat], [RewardResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banModule' : IDL.Func([IDL.Text], [ModuleBanResult], []),
  'claimAdmin' : IDL.Func([IDL.Text], [ClaimResult], []),
  'claimSpinReward' : IDL.Func([IDL.Nat], [SpinWheelResult], []),
  'declineFriendRequest' : IDL.Func([IDL.Principal], [FriendResult], []),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAllModuleStatuses' : IDL.Func([], [IDL.Vec(ModuleStatus)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
  'getBannedModules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerRewards' : IDL.Func([], [IDL.Opt(Reward)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
  'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
  'getFriendsList' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
  'getLastSpinTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
  'getOnlineUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
  'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'getRemainingSpinCooldown' : IDL.Func([], [IDL.Nat], ['query']),
  'getSpinRewards' : IDL.Func([], [IDL.Vec(SpinReward)], ['query']),
  'getTotalScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserActivity' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ActivityEvent)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVirtualPetHub' : IDL.Func([], [IDL.Opt(VirtualPetHub)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], []),
  'isClaimedAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'recordActivity' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordSpinReward' : IDL.Func([SpinReward], [], []),
  'removeFriend' : IDL.Func([IDL.Principal], [FriendResult], []),
  'requestApproval' : IDL.Func([], [], []),
  'resetAdmin' : IDL.Func([], [ResetResult], []),
  'saveCallerRewards' : IDL.Func([Reward], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVirtualPetHub' : IDL.Func([VirtualPetHub], [], []),
  'sendChatMessage' : IDL.Func([IDL.Principal, IDL.Text], [ChatResult], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [FriendResult], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'unbanModule' : IDL.Func([IDL.Text], [ModuleBanResult], []),
  'updatePresence' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FriendResult = IDL.Variant({
    'alreadyFriends' : IDL.Null,
    'sent' : IDL.Null,
    'alreadyRequested' : IDL.Null,
    'notFound' : IDL.Null,
    'selfRequest' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
    'alreadyAccepted' : IDL.Null,
    'removed' : IDL.Null,
  });
  const RewardResult = IDL.Variant({
    'sent' : IDL.Null,
    'notFound' : IDL.Null,
    'notAdmin' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ModuleBanResult = IDL.Variant({
    'banned' : IDL.Null,
    'unbanned' : IDL.Null,
    'notBanned' : IDL.Null,
    'alreadyBanned' : IDL.Null,
  });
  const ClaimResult = IDL.Variant({
    'claimed' : IDL.Null,
    'alreadyClaimed' : IDL.Record({ 'admin' : IDL.Principal }),
  });
  const SpinWheelResult = IDL.Record({
    'remainingCooldown' : IDL.Nat,
    'pointsAdded' : IDL.Nat,
    'message' : IDL.Text,
  });
  const ModuleStatus = IDL.Record({
    'moduleId' : IDL.Text,
    'banned' : IDL.Bool,
  });
  const AvatarConfigRef = IDL.Record({
    'body' : IDL.Text,
    'hair' : IDL.Text,
    'head' : IDL.Text,
    'headwear' : IDL.Text,
    'shoes' : IDL.Text,
    'pants' : IDL.Text,
  });
  const AdminUserView = IDL.Record({
    'status' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'lastSeen' : IDL.Int,
    'avatarConfig' : IDL.Opt(AvatarConfigRef),
  });
  const Reward = IDL.Record({
    'userId' : IDL.Principal,
    'badges' : IDL.Vec(IDL.Text),
    'achievements' : IDL.Vec(IDL.Text),
    'totalTrophies' : IDL.Nat,
    'virtualPetLevel' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const AvatarConfig = IDL.Record({
    'body' : IDL.Text,
    'hair' : IDL.Text,
    'head' : IDL.Text,
    'headwear' : IDL.Text,
    'shoes' : IDL.Text,
    'pants' : IDL.Text,
  });
  const AccessibilitySettings = IDL.Record({
    'highContrastMode' : IDL.Bool,
    'largeText' : IDL.Bool,
    'readAloudEnabled' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'mascotPreference' : IDL.Text,
    'theme' : IDL.Text,
    'approvedContacts' : IDL.Vec(IDL.Principal),
    'parentPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'screenTimeLimit' : IDL.Nat,
    'avatarUrl' : IDL.Text,
    'contentFilterLevel' : IDL.Text,
    'avatarConfig' : IDL.Opt(AvatarConfig),
    'accessibilitySettings' : AccessibilitySettings,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'threadId' : IDL.Text,
  });
  const ChatThread = IDL.Record({
    'lastMessageAt' : IDL.Int,
    'name' : IDL.Text,
    'lastMessage' : IDL.Text,
    'friend' : IDL.Principal,
  });
  const FriendRequest = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Principal,
    'createdAt' : IDL.Int,
  });
  const Friend = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'online' : IDL.Bool,
  });
  const ActivityEvent = IDL.Record({
    'principal' : IDL.Principal,
    'metadata' : IDL.Text,
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
  });
  const SpinReward = IDL.Record({
    'value' : IDL.Text,
    'rewardType' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const VirtualPetHub = IDL.Record({
    'growthStage' : IDL.Nat,
    'accessories' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'warnedAboutExtremeChanges' : IDL.Bool,
    'happinessLevel' : IDL.Nat,
    'petName' : IDL.Text,
    'trophies' : IDL.Nat,
    'homeStyle' : IDL.Text,
    'decorations' : IDL.Vec(IDL.Text),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const ResetResult = IDL.Variant({ 'reset' : IDL.Null, 'noAdmin' : IDL.Null });
  const ChatResult = IDL.Variant({
    'sent' : IDL.Null,
    'banned' : IDL.Null,
    'notFriends' : IDL.Null,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [FriendResult], []),
    'adminSendReward' : IDL.Func([IDL.Principal, IDL.Nat], [RewardResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banModule' : IDL.Func([IDL.Text], [ModuleBanResult], []),
    'claimAdmin' : IDL.Func([IDL.Text], [ClaimResult], []),
    'claimSpinReward' : IDL.Func([IDL.Nat], [SpinWheelResult], []),
    'declineFriendRequest' : IDL.Func([IDL.Principal], [FriendResult], []),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAllModuleStatuses' : IDL.Func([], [IDL.Vec(ModuleStatus)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
    'getBannedModules' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerRewards' : IDL.Func([], [IDL.Opt(Reward)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getChatThreads' : IDL.Func([], [IDL.Vec(ChatThread)], ['query']),
    'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(Friend)], ['query']),
    'getFriendsList' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
    'getLastSpinTime' : IDL.Func([], [IDL.Opt(IDL.Int)], ['query']),
    'getOnlineUsers' : IDL.Func([], [IDL.Vec(AdminUserView)], ['query']),
    'getRecentActivity' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'getRemainingSpinCooldown' : IDL.Func([], [IDL.Nat], ['query']),
    'getSpinRewards' : IDL.Func([], [IDL.Vec(SpinReward)], ['query']),
    'getTotalScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserActivity' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ActivityEvent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVirtualPetHub' : IDL.Func([], [IDL.Opt(VirtualPetHub)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], []),
    'isClaimedAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'recordActivity' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordSpinReward' : IDL.Func([SpinReward], [], []),
    'removeFriend' : IDL.Func([IDL.Principal], [FriendResult], []),
    'requestApproval' : IDL.Func([], [], []),
    'resetAdmin' : IDL.Func([], [ResetResult], []),
    'saveCallerRewards' : IDL.Func([Reward], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVirtualPetHub' : IDL.Func([VirtualPetHub], [], []),
    'sendChatMessage' : IDL.Func([IDL.Principal, IDL.Text], [ChatResult], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [FriendResult], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'unbanModule' : IDL.Func([IDL.Text], [ModuleBanResult], []),
    'updatePresence' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };