/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessibilitySettings {
  'highContrastMode' : boolean,
  'largeText' : boolean,
  'readAloudEnabled' : boolean,
}
export interface ActivityEvent {
  'principal' : Principal,
  'metadata' : string,
  'timestamp' : bigint,
  'eventType' : string,
}
export interface AdminUserView {
  'status' : string,
  'principal' : Principal,
  'name' : string,
  'lastSeen' : bigint,
  'avatarConfig' : [] | [AvatarConfigRef],
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AvatarConfig {
  'body' : string,
  'hair' : string,
  'head' : string,
  'headwear' : string,
  'shoes' : string,
  'pants' : string,
}
export interface AvatarConfigRef {
  'body' : string,
  'hair' : string,
  'head' : string,
  'headwear' : string,
  'shoes' : string,
  'pants' : string,
}
export type ChatResult = { 'sent' : null } |
  { 'banned' : null } |
  { 'notFriends' : null };
export interface ChatThread {
  'lastMessageAt' : bigint,
  'name' : string,
  'lastMessage' : string,
  'friend' : Principal,
}
export type ClaimResult = { 'claimed' : null } |
  { 'alreadyClaimed' : { 'admin' : Principal } };
export interface Friend {
  'principal' : Principal,
  'name' : string,
  'online' : boolean,
}
export interface FriendRequest {
  'to' : Principal,
  'from' : Principal,
  'createdAt' : bigint,
}
export type FriendResult = { 'alreadyFriends' : null } |
  { 'sent' : null } |
  { 'alreadyRequested' : null } |
  { 'notFound' : null } |
  { 'selfRequest' : null } |
  { 'accepted' : null } |
  { 'declined' : null } |
  { 'alreadyAccepted' : null } |
  { 'removed' : null };
export interface Message {
  'id' : bigint,
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : bigint,
  'threadId' : string,
}
export type ModuleBanResult = { 'banned' : null } |
  { 'unbanned' : null } |
  { 'notBanned' : null } |
  { 'alreadyBanned' : null };
export interface ModuleStatus { 'moduleId' : string, 'banned' : boolean }
export type ResetResult = { 'reset' : null } |
  { 'noAdmin' : null };
export interface Reward {
  'userId' : Principal,
  'badges' : Array<string>,
  'achievements' : Array<string>,
  'totalTrophies' : bigint,
  'virtualPetLevel' : bigint,
  'points' : bigint,
}
export type RewardResult = { 'sent' : null } |
  { 'notFound' : null } |
  { 'notAdmin' : null };
export interface SpinReward {
  'value' : string,
  'rewardType' : string,
  'timestamp' : bigint,
}
export interface SpinWheelResult {
  'remainingCooldown' : bigint,
  'pointsAdded' : bigint,
  'message' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'age' : bigint,
  'mascotPreference' : string,
  'theme' : string,
  'approvedContacts' : Array<Principal>,
  'parentPrincipal' : Principal,
  'name' : string,
  'screenTimeLimit' : bigint,
  'avatarUrl' : string,
  'contentFilterLevel' : string,
  'avatarConfig' : [] | [AvatarConfig],
  'accessibilitySettings' : AccessibilitySettings,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VirtualPetHub {
  'growthStage' : bigint,
  'accessories' : Array<string>,
  'userId' : Principal,
  'warnedAboutExtremeChanges' : boolean,
  'happinessLevel' : bigint,
  'petName' : string,
  'trophies' : bigint,
  'homeStyle' : string,
  'decorations' : Array<string>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], FriendResult>,
  'adminSendReward' : ActorMethod<[Principal, bigint], RewardResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banModule' : ActorMethod<[string], ModuleBanResult>,
  'claimAdmin' : ActorMethod<[string], ClaimResult>,
  'claimSpinReward' : ActorMethod<[bigint], SpinWheelResult>,
  'declineFriendRequest' : ActorMethod<[Principal], FriendResult>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getAllModuleStatuses' : ActorMethod<[], Array<ModuleStatus>>,
  'getAllUsers' : ActorMethod<[], Array<AdminUserView>>,
  'getBannedModules' : ActorMethod<[], Array<string>>,
  'getCallerRewards' : ActorMethod<[], [] | [Reward]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatMessages' : ActorMethod<[Principal], Array<Message>>,
  'getChatThreads' : ActorMethod<[], Array<ChatThread>>,
  'getFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getFriends' : ActorMethod<[], Array<Friend>>,
  'getFriendsList' : ActorMethod<[], Array<AdminUserView>>,
  'getLastSpinTime' : ActorMethod<[], [] | [bigint]>,
  'getOnlineUsers' : ActorMethod<[], Array<AdminUserView>>,
  'getRecentActivity' : ActorMethod<[], Array<ActivityEvent>>,
  'getRemainingSpinCooldown' : ActorMethod<[], bigint>,
  'getSpinRewards' : ActorMethod<[], Array<SpinReward>>,
  'getTotalScore' : ActorMethod<[], bigint>,
  'getUserActivity' : ActorMethod<[Principal], Array<ActivityEvent>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVirtualPetHub' : ActorMethod<[], [] | [VirtualPetHub]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isClaimedAdmin' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'recordActivity' : ActorMethod<[string, string], undefined>,
  'recordSpinReward' : ActorMethod<[SpinReward], undefined>,
  'removeFriend' : ActorMethod<[Principal], FriendResult>,
  'requestApproval' : ActorMethod<[], undefined>,
  'resetAdmin' : ActorMethod<[], ResetResult>,
  'saveCallerRewards' : ActorMethod<[Reward], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveVirtualPetHub' : ActorMethod<[VirtualPetHub], undefined>,
  'sendChatMessage' : ActorMethod<[Principal, string], ChatResult>,
  'sendFriendRequest' : ActorMethod<[Principal], FriendResult>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'unbanModule' : ActorMethod<[string], ModuleBanResult>,
  'updatePresence' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];