// Expanded Craft & DIY project catalog
export interface CraftProjectData {
  id: string;
  category: "Art" | "Science" | "Cooking" | "Seasonal";
  title: string;
  difficulty: "Easy" | "Medium" | "Hard";
  steps: string[];
  materials: string[];
  safetyTips: string[];
  badges: string[];
}

export const craftDiyProjects: CraftProjectData[] = [
  // Art Projects
  {
    id: "art-1",
    category: "Art",
    title: "Paper Plate Animals",
    difficulty: "Easy",
    steps: [
      "Gather paper plates, markers, and glue",
      "Draw animal face on the plate",
      "Cut out ears from extra plates",
      "Glue ears to the main plate",
      "Add details with markers",
    ],
    materials: ["Paper plates", "Markers", "Glue", "Scissors"],
    safetyTips: ["Use child-safe scissors", "Adult supervision recommended"],
    badges: ["First Craft", "Animal Artist"],
  },
  {
    id: "art-2",
    category: "Art",
    title: "Rainbow Salt Painting",
    difficulty: "Easy",
    steps: [
      "Draw a design with glue on paper",
      "Sprinkle salt over the glue",
      "Let it dry for a few minutes",
      "Use watercolors to paint the salt",
      "Watch the colors spread and blend",
    ],
    materials: ["White glue", "Salt", "Watercolors", "Paper", "Paintbrush"],
    safetyTips: ["Use non-toxic glue and paints", "Cover work surface"],
    badges: ["Color Master", "Salt Artist"],
  },
  {
    id: "art-3",
    category: "Art",
    title: "Handprint Flower Garden",
    difficulty: "Easy",
    steps: [
      "Paint your hand with bright colors",
      "Press hand onto paper to make flowers",
      "Repeat with different colors",
      "Use green paint to add stems and leaves",
      "Let dry and display your garden",
    ],
    materials: ["Washable paint", "Paper", "Paintbrush", "Water for cleanup"],
    safetyTips: ["Use washable, non-toxic paint", "Protect clothing"],
    badges: ["Handprint Hero", "Garden Creator"],
  },
  {
    id: "art-4",
    category: "Art",
    title: "Cardboard Box Castle",
    difficulty: "Medium",
    steps: [
      "Collect cardboard boxes of different sizes",
      "Cut out doors and windows",
      "Stack and glue boxes together",
      "Paint the castle with bright colors",
      "Add flags and decorations",
    ],
    materials: ["Cardboard boxes", "Scissors", "Glue", "Paint", "Markers"],
    safetyTips: ["Adult help with cutting", "Use non-toxic paint"],
    badges: ["Castle Builder", "Architect"],
  },
  {
    id: "art-5",
    category: "Art",
    title: "Tissue Paper Stained Glass",
    difficulty: "Medium",
    steps: [
      "Cut tissue paper into small pieces",
      "Draw a design on clear contact paper",
      "Stick tissue paper pieces onto the design",
      "Cover with another sheet of contact paper",
      "Hang in a window to see the light shine through",
    ],
    materials: ["Tissue paper", "Clear contact paper", "Scissors"],
    safetyTips: ["Use child-safe scissors", "Adult help with contact paper"],
    badges: ["Light Artist", "Window Decorator"],
  },
  {
    id: "art-6",
    category: "Art",
    title: "Nature Collage",
    difficulty: "Easy",
    steps: [
      "Go on a nature walk and collect leaves, flowers, and twigs",
      "Arrange items on paper in a design",
      "Glue items down carefully",
      "Add details with markers if desired",
      "Let dry completely",
    ],
    materials: ["Natural items", "Paper", "Glue", "Markers"],
    safetyTips: [
      "Only collect fallen items",
      "Wash hands after handling nature items",
    ],
    badges: ["Nature Explorer", "Collage Artist"],
  },
  {
    id: "art-7",
    category: "Art",
    title: "Sock Puppets",
    difficulty: "Medium",
    steps: [
      "Choose a clean sock",
      "Glue on buttons for eyes",
      "Add yarn for hair",
      "Use felt to make a mouth",
      "Decorate with markers and fabric scraps",
    ],
    materials: ["Old socks", "Buttons", "Yarn", "Felt", "Glue", "Markers"],
    safetyTips: ["Use fabric glue", "Adult supervision with small parts"],
    badges: ["Puppet Master", "Character Creator"],
  },
  {
    id: "art-8",
    category: "Art",
    title: "Marble Painting",
    difficulty: "Easy",
    steps: [
      "Place paper in a shallow box",
      "Dip marbles in different paint colors",
      "Drop marbles onto paper",
      "Tilt box to roll marbles around",
      "Create unique patterns and designs",
    ],
    materials: ["Marbles", "Paint", "Paper", "Shallow box"],
    safetyTips: [
      "Supervise to prevent marble choking hazard",
      "Use washable paint",
    ],
    badges: ["Marble Artist", "Pattern Maker"],
  },

  // Science Projects
  {
    id: "science-1",
    category: "Science",
    title: "Volcano Eruption",
    difficulty: "Medium",
    steps: [
      "Build a volcano shape with clay",
      "Place a small cup in the center",
      "Add baking soda to the cup",
      "Pour vinegar and watch it erupt!",
      "Add food coloring for extra fun",
    ],
    materials: ["Baking soda", "Vinegar", "Clay", "Food coloring", "Small cup"],
    safetyTips: ["Do this outside or on a tray", "Wear old clothes"],
    badges: ["Science Explorer", "Volcano Master"],
  },
  {
    id: "science-2",
    category: "Science",
    title: "Rainbow in a Jar",
    difficulty: "Medium",
    steps: [
      "Mix sugar and water in different concentrations",
      "Add food coloring to each mixture",
      "Carefully layer liquids from heaviest to lightest",
      "Watch the rainbow form in the jar",
      "Learn about density",
    ],
    materials: ["Sugar", "Water", "Food coloring", "Clear jar", "Spoon"],
    safetyTips: ["Adult supervision with pouring", "Do not drink the mixture"],
    badges: ["Rainbow Scientist", "Density Detective"],
  },
  {
    id: "science-3",
    category: "Science",
    title: "Magic Milk Experiment",
    difficulty: "Easy",
    steps: [
      "Pour milk into a shallow dish",
      "Add drops of food coloring",
      "Dip a cotton swab in dish soap",
      "Touch the soap to the milk",
      "Watch the colors swirl and dance",
    ],
    materials: [
      "Milk",
      "Food coloring",
      "Dish soap",
      "Cotton swabs",
      "Shallow dish",
    ],
    safetyTips: ["Do not drink the milk after experiment", "Adult supervision"],
    badges: ["Color Scientist", "Chemistry Kid"],
  },
  {
    id: "science-4",
    category: "Science",
    title: "Grow Crystal Snowflakes",
    difficulty: "Hard",
    steps: [
      "Shape pipe cleaners into snowflake forms",
      "Boil water and dissolve borax (adult help)",
      "Hang snowflakes in the solution overnight",
      "Watch crystals grow on the pipe cleaners",
      "Remove and let dry to display",
    ],
    materials: ["Pipe cleaners", "Borax", "Water", "String", "Jar"],
    safetyTips: ["Adult supervision required", "Do not touch borax directly"],
    badges: ["Crystal Grower", "Winter Scientist"],
  },
  {
    id: "science-5",
    category: "Science",
    title: "Homemade Slime",
    difficulty: "Easy",
    steps: [
      "Mix glue and water in a bowl",
      "Add food coloring if desired",
      "In another bowl, mix borax and water",
      "Slowly add borax solution to glue mixture",
      "Stir until slime forms, then knead with hands",
    ],
    materials: ["White glue", "Borax", "Water", "Food coloring", "Bowls"],
    safetyTips: ["Adult supervision", "Wash hands after playing"],
    badges: ["Slime Master", "Texture Explorer"],
  },
  {
    id: "science-6",
    category: "Science",
    title: "Balloon Rocket",
    difficulty: "Easy",
    steps: [
      "Thread a string through a straw",
      "Tie the string between two points",
      "Blow up a balloon and tape it to the straw",
      "Let go and watch the balloon rocket fly",
      "Experiment with different balloon sizes",
    ],
    materials: ["Balloon", "String", "Straw", "Tape"],
    safetyTips: [
      "Clear the flight path",
      "Adult supervision for young children",
    ],
    badges: ["Rocket Scientist", "Physics Explorer"],
  },
  {
    id: "science-7",
    category: "Science",
    title: "Walking Water Experiment",
    difficulty: "Medium",
    steps: [
      "Fill three cups with water",
      "Add different food coloring to each cup",
      "Place empty cups between the colored ones",
      "Connect cups with paper towels",
      'Watch water "walk" and colors mix',
    ],
    materials: ["Cups", "Water", "Food coloring", "Paper towels"],
    safetyTips: ["Use a tray to catch spills", "Adult supervision"],
    badges: ["Water Scientist", "Color Mixer"],
  },
  {
    id: "science-8",
    category: "Science",
    title: "Egg in a Bottle",
    difficulty: "Hard",
    steps: [
      "Peel a hard-boiled egg",
      "Light a small piece of paper (adult only)",
      "Drop burning paper into a bottle",
      "Quickly place egg on bottle opening",
      "Watch the egg get sucked inside",
    ],
    materials: ["Hard-boiled egg", "Glass bottle", "Paper", "Matches"],
    safetyTips: ["Adult must handle fire", "Use heat-safe bottle"],
    badges: ["Pressure Expert", "Science Master"],
  },

  // Cooking Projects
  {
    id: "cooking-1",
    category: "Cooking",
    title: "No-Bake Energy Balls",
    difficulty: "Easy",
    steps: [
      "Mix oats, honey, and peanut butter in a bowl",
      "Add chocolate chips or raisins",
      "Roll mixture into small balls",
      "Refrigerate for 30 minutes",
      "Enjoy your healthy snack",
    ],
    materials: ["Oats", "Honey", "Peanut butter", "Chocolate chips", "Bowl"],
    safetyTips: ["Check for nut allergies", "Wash hands before cooking"],
    badges: ["Chef in Training", "Healthy Snacker"],
  },
  {
    id: "cooking-2",
    category: "Cooking",
    title: "Fruit Kabobs",
    difficulty: "Easy",
    steps: [
      "Wash and cut fruit into bite-sized pieces",
      "Thread fruit onto wooden skewers",
      "Arrange in a colorful pattern",
      "Serve with yogurt dip",
      "Enjoy your rainbow snack",
    ],
    materials: ["Assorted fruits", "Wooden skewers", "Yogurt", "Cutting board"],
    safetyTips: [
      "Adult help with cutting",
      "Use blunt skewers for young children",
    ],
    badges: ["Fruit Artist", "Healthy Eater"],
  },
  {
    id: "cooking-3",
    category: "Cooking",
    title: "Homemade Pizza",
    difficulty: "Medium",
    steps: [
      "Roll out pizza dough on a floured surface",
      "Spread tomato sauce on the dough",
      "Add cheese and your favorite toppings",
      "Bake in the oven (adult supervision)",
      "Let cool and enjoy",
    ],
    materials: [
      "Pizza dough",
      "Tomato sauce",
      "Cheese",
      "Toppings",
      "Baking sheet",
    ],
    safetyTips: ["Adult supervision with oven", "Use oven mitts"],
    badges: ["Pizza Chef", "Kitchen Helper"],
  },
  {
    id: "cooking-4",
    category: "Cooking",
    title: "Smoothie Bowl",
    difficulty: "Easy",
    steps: [
      "Blend frozen fruit with yogurt or milk",
      "Pour into a bowl",
      "Top with granola, fresh fruit, and seeds",
      "Create a colorful design",
      "Eat with a spoon and enjoy",
    ],
    materials: ["Frozen fruit", "Yogurt", "Granola", "Fresh fruit", "Blender"],
    safetyTips: ["Adult help with blender", "Check for allergies"],
    badges: ["Smoothie Master", "Breakfast Chef"],
  },
  {
    id: "cooking-5",
    category: "Cooking",
    title: "Decorated Cookies",
    difficulty: "Medium",
    steps: [
      "Bake sugar cookies (or use store-bought)",
      "Mix powdered sugar with milk for icing",
      "Add food coloring to create different colors",
      "Decorate cookies with icing and sprinkles",
      "Let dry before eating",
    ],
    materials: [
      "Sugar cookies",
      "Powdered sugar",
      "Milk",
      "Food coloring",
      "Sprinkles",
    ],
    safetyTips: [
      "Adult supervision with baking",
      "Wash hands before decorating",
    ],
    badges: ["Cookie Decorator", "Sweet Artist"],
  },
  {
    id: "cooking-6",
    category: "Cooking",
    title: "Veggie Faces",
    difficulty: "Easy",
    steps: [
      "Spread cream cheese or hummus on a plate",
      "Use vegetables to create a funny face",
      "Cherry tomatoes for eyes, carrot for nose",
      "Cucumber slices for ears",
      "Take a photo before eating",
    ],
    materials: ["Cream cheese or hummus", "Assorted vegetables", "Plate"],
    safetyTips: ["Wash all vegetables", "Adult help with cutting"],
    badges: ["Veggie Artist", "Healthy Creator"],
  },
  {
    id: "cooking-7",
    category: "Cooking",
    title: "Homemade Popsicles",
    difficulty: "Easy",
    steps: [
      "Blend fruit with juice or yogurt",
      "Pour mixture into popsicle molds",
      "Insert sticks",
      "Freeze for at least 4 hours",
      "Run mold under warm water to remove",
    ],
    materials: [
      "Fruit",
      "Juice or yogurt",
      "Popsicle molds",
      "Sticks",
      "Blender",
    ],
    safetyTips: ["Adult help with blender", "Wait until fully frozen"],
    badges: ["Popsicle Maker", "Frozen Treat Chef"],
  },
  {
    id: "cooking-8",
    category: "Cooking",
    title: "Trail Mix",
    difficulty: "Easy",
    steps: [
      "Choose your favorite nuts and seeds",
      "Add dried fruit like raisins or cranberries",
      "Mix in some chocolate chips or M&Ms",
      "Combine everything in a large bowl",
      "Portion into small bags for snacks",
    ],
    materials: ["Nuts", "Seeds", "Dried fruit", "Chocolate chips", "Bowl"],
    safetyTips: ["Check for nut allergies", "Wash hands before mixing"],
    badges: ["Snack Master", "Mix Creator"],
  },

  // Seasonal Projects
  {
    id: "seasonal-1",
    category: "Seasonal",
    title: "Halloween Pumpkin Painting",
    difficulty: "Easy",
    steps: [
      "Choose a small pumpkin",
      "Paint the pumpkin with acrylic paints",
      "Create a fun face or design",
      "Add glitter or stickers for decoration",
      "Let dry and display",
    ],
    materials: [
      "Small pumpkin",
      "Acrylic paint",
      "Paintbrushes",
      "Glitter",
      "Stickers",
    ],
    safetyTips: ["Use non-toxic paint", "Cover work surface"],
    badges: ["Halloween Artist", "Pumpkin Painter"],
  },
  {
    id: "seasonal-2",
    category: "Seasonal",
    title: "Christmas Ornaments",
    difficulty: "Medium",
    steps: [
      "Cut shapes from felt or foam",
      "Decorate with glitter, sequins, and markers",
      "Glue on a ribbon loop for hanging",
      "Add your name and the year",
      "Hang on the tree",
    ],
    materials: ["Felt or foam", "Glitter", "Sequins", "Ribbon", "Glue"],
    safetyTips: ["Use child-safe scissors", "Adult supervision with glue gun"],
    badges: ["Ornament Maker", "Holiday Crafter"],
  },
  {
    id: "seasonal-3",
    category: "Seasonal",
    title: "Valentine Cards",
    difficulty: "Easy",
    steps: [
      "Fold construction paper in half",
      "Cut out heart shapes from colored paper",
      "Glue hearts onto the card",
      "Write a sweet message inside",
      "Decorate with stickers and glitter",
    ],
    materials: [
      "Construction paper",
      "Scissors",
      "Glue",
      "Markers",
      "Stickers",
    ],
    safetyTips: ["Use child-safe scissors", "Supervise glitter use"],
    badges: ["Valentine Artist", "Card Maker"],
  },
  {
    id: "seasonal-4",
    category: "Seasonal",
    title: "Easter Egg Decorating",
    difficulty: "Easy",
    steps: [
      "Hard boil eggs (adult help)",
      "Let eggs cool completely",
      "Dye eggs in food coloring and vinegar",
      "Decorate with stickers or markers",
      "Display in an egg carton",
    ],
    materials: ["Eggs", "Food coloring", "Vinegar", "Stickers", "Markers"],
    safetyTips: ["Adult supervision with boiling", "Handle eggs gently"],
    badges: ["Easter Artist", "Egg Decorator"],
  },
  {
    id: "seasonal-5",
    category: "Seasonal",
    title: "Thanksgiving Turkey Hand",
    difficulty: "Easy",
    steps: [
      "Trace your hand on brown paper",
      "Cut out the hand shape",
      "Glue colorful feathers to the fingers",
      "Add googly eyes and a beak",
      "Write what you are thankful for",
    ],
    materials: ["Brown paper", "Scissors", "Feathers", "Googly eyes", "Glue"],
    safetyTips: ["Use child-safe scissors", "Adult supervision"],
    badges: ["Thanksgiving Crafter", "Gratitude Artist"],
  },
  {
    id: "seasonal-6",
    category: "Seasonal",
    title: "Summer Sun Catchers",
    difficulty: "Medium",
    steps: [
      "Cut shapes from clear plastic lids",
      "Color with permanent markers",
      "Punch a hole at the top",
      "Thread with string or ribbon",
      "Hang in a sunny window",
    ],
    materials: [
      "Clear plastic lids",
      "Permanent markers",
      "Hole punch",
      "String",
    ],
    safetyTips: ["Adult help with hole punch", "Use in well-ventilated area"],
    badges: ["Sun Catcher Maker", "Summer Artist"],
  },
  {
    id: "seasonal-7",
    category: "Seasonal",
    title: "Spring Flower Pots",
    difficulty: "Medium",
    steps: [
      "Paint a small terracotta pot",
      "Let the paint dry completely",
      "Fill with soil",
      "Plant flower seeds or a small plant",
      "Water and place in sunlight",
    ],
    materials: ["Terracotta pot", "Paint", "Soil", "Seeds or plant", "Water"],
    safetyTips: ["Use non-toxic paint", "Wash hands after handling soil"],
    badges: ["Gardener", "Spring Crafter"],
  },
  {
    id: "seasonal-8",
    category: "Seasonal",
    title: "Winter Snowflakes",
    difficulty: "Easy",
    steps: [
      "Fold white paper into quarters",
      "Cut small shapes along the edges",
      "Unfold to reveal your snowflake",
      "Decorate with glitter if desired",
      "Hang in windows or on walls",
    ],
    materials: ["White paper", "Scissors", "Glitter (optional)", "String"],
    safetyTips: ["Use child-safe scissors", "Adult supervision"],
    badges: ["Snowflake Artist", "Winter Crafter"],
  },
];
