/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface ModuleStatus {
    moduleId: string;
    banned: boolean;
}
export interface VirtualPetHub {
    growthStage: bigint;
    accessories: Array<string>;
    userId: Principal;
    warnedAboutExtremeChanges: boolean;
    happinessLevel: bigint;
    petName: string;
    trophies: bigint;
    homeStyle: string;
    decorations: Array<string>;
}
export interface Reward {
    userId: Principal;
    badges: Array<string>;
    achievements: Array<string>;
    totalTrophies: bigint;
    virtualPetLevel: bigint;
    points: bigint;
}
export interface SpinWheelResult {
    remainingCooldown: bigint;
    pointsAdded: bigint;
    message: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ClaimResult = {
    __kind__: "claimed";
    claimed: null;
} | {
    __kind__: "alreadyClaimed";
    alreadyClaimed: {
        admin: Principal;
    };
};
export interface Friend {
    principal: Principal;
    name: string;
    online: boolean;
}
export interface SpinReward {
    value: string;
    rewardType: string;
    timestamp: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface FriendRequest {
    to: Principal;
    from: Principal;
    createdAt: bigint;
}
export interface ChatThread {
    lastMessageAt: bigint;
    name: string;
    lastMessage: string;
    friend: Principal;
}
export interface AvatarConfigRef {
    body: string;
    hair: string;
    head: string;
    headwear: string;
    shoes: string;
    pants: string;
}
export interface AdminUserView {
    status: string;
    principal: Principal;
    name: string;
    lastSeen: bigint;
    avatarConfig?: AvatarConfigRef;
}
export interface Message {
    id: bigint;
    content: string;
    recipient: Principal;
    sender: Principal;
    timestamp: bigint;
    threadId: string;
}
export interface AvatarConfig {
    body: string;
    hair: string;
    head: string;
    headwear: string;
    shoes: string;
    pants: string;
}
export interface ActivityEvent {
    principal: Principal;
    metadata: string;
    timestamp: bigint;
    eventType: string;
}
export interface AccessibilitySettings {
    highContrastMode: boolean;
    largeText: boolean;
    readAloudEnabled: boolean;
}
export interface UserProfile {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig?: AvatarConfig;
    accessibilitySettings: AccessibilitySettings;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ChatResult {
    sent = "sent",
    banned = "banned",
    notFriends = "notFriends"
}
export enum FriendResult {
    alreadyFriends = "alreadyFriends",
    sent = "sent",
    alreadyRequested = "alreadyRequested",
    notFound = "notFound",
    selfRequest = "selfRequest",
    accepted = "accepted",
    declined = "declined",
    alreadyAccepted = "alreadyAccepted",
    removed = "removed"
}
export enum ModuleBanResult {
    banned = "banned",
    unbanned = "unbanned",
    notBanned = "notBanned",
    alreadyBanned = "alreadyBanned"
}
export enum ResetResult {
    reset = "reset",
    noAdmin = "noAdmin"
}
export enum RewardResult {
    sent = "sent",
    notFound = "notFound",
    notAdmin = "notAdmin"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptFriendRequest(fromPrincipal: Principal): Promise<FriendResult>;
    adminSendReward(toPrincipal: Principal, points: bigint): Promise<RewardResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banModule(moduleId: string): Promise<ModuleBanResult>;
    claimAdmin(password: string): Promise<ClaimResult>;
    claimSpinReward(points: bigint): Promise<SpinWheelResult>;
    declineFriendRequest(fromPrincipal: Principal): Promise<FriendResult>;
    getAdminPrincipal(): Promise<Principal | null>;
    getAllModuleStatuses(): Promise<Array<ModuleStatus>>;
    getAllUsers(): Promise<Array<AdminUserView>>;
    getBannedModules(): Promise<Array<string>>;
    getCallerRewards(): Promise<Reward | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatMessages(withPrincipal: Principal): Promise<Array<Message>>;
    getChatThreads(): Promise<Array<ChatThread>>;
    getFriendRequests(): Promise<Array<FriendRequest>>;
    getFriends(): Promise<Array<Friend>>;
    getFriendsList(): Promise<Array<AdminUserView>>;
    getLastSpinTime(): Promise<bigint | null>;
    getOnlineUsers(): Promise<Array<AdminUserView>>;
    getRecentActivity(): Promise<Array<ActivityEvent>>;
    getRemainingSpinCooldown(): Promise<bigint>;
    getSpinRewards(): Promise<Array<SpinReward>>;
    getTotalScore(): Promise<bigint>;
    getUserActivity(userPrincipal: Principal): Promise<Array<ActivityEvent>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVirtualPetHub(): Promise<VirtualPetHub | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isClaimedAdmin(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    recordActivity(eventType: string, metadata: string): Promise<void>;
    recordSpinReward(reward: SpinReward): Promise<void>;
    removeFriend(friendPrincipal: Principal): Promise<FriendResult>;
    requestApproval(): Promise<void>;
    resetAdmin(): Promise<ResetResult>;
    saveCallerRewards(reward: Reward): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveVirtualPetHub(pet: VirtualPetHub): Promise<void>;
    sendChatMessage(toPrincipal: Principal, text: string): Promise<ChatResult>;
    sendFriendRequest(toPrincipal: Principal): Promise<FriendResult>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    unbanModule(moduleId: string): Promise<ModuleBanResult>;
    updatePresence(): Promise<void>;
}
import type { AccessibilitySettings as _AccessibilitySettings, AdminUserView as _AdminUserView, ApprovalStatus as _ApprovalStatus, AvatarConfig as _AvatarConfig, AvatarConfigRef as _AvatarConfigRef, ChatResult as _ChatResult, ClaimResult as _ClaimResult, FriendResult as _FriendResult, ModuleBanResult as _ModuleBanResult, ResetResult as _ResetResult, Reward as _Reward, RewardResult as _RewardResult, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, VirtualPetHub as _VirtualPetHub, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptFriendRequest(arg0: Principal): Promise<FriendResult> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSendReward(arg0: Principal, arg1: bigint): Promise<RewardResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSendReward(arg0, arg1);
                return from_candid_RewardResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSendReward(arg0, arg1);
            return from_candid_RewardResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banModule(arg0: string): Promise<ModuleBanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.banModule(arg0);
                return from_candid_ModuleBanResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banModule(arg0);
            return from_candid_ModuleBanResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimAdmin(arg0: string): Promise<ClaimResult> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin(arg0);
                return from_candid_ClaimResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin(arg0);
            return from_candid_ClaimResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async claimSpinReward(arg0: bigint): Promise<SpinWheelResult> {
        if (this.processError) {
            try {
                const result = await this.actor.claimSpinReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimSpinReward(arg0);
            return result;
        }
    }
    async declineFriendRequest(arg0: Principal): Promise<FriendResult> {
        if (this.processError) {
            try {
                const result = await this.actor.declineFriendRequest(arg0);
                return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineFriendRequest(arg0);
            return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllModuleStatuses(): Promise<Array<ModuleStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModuleStatuses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModuleStatuses();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBannedModules(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBannedModules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBannedModules();
            return result;
        }
    }
    async getCallerRewards(): Promise<Reward | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRewards();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRewards();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages(arg0);
            return result;
        }
    }
    async getChatThreads(): Promise<Array<ChatThread>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatThreads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatThreads();
            return result;
        }
    }
    async getFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return result;
        }
    }
    async getFriends(): Promise<Array<Friend>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return result;
        }
    }
    async getFriendsList(): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsList();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsList();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastSpinTime(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastSpinTime();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastSpinTime();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnlineUsers(): Promise<Array<AdminUserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlineUsers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlineUsers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentActivity(): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentActivity();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentActivity();
            return result;
        }
    }
    async getRemainingSpinCooldown(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingSpinCooldown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingSpinCooldown();
            return result;
        }
    }
    async getSpinRewards(): Promise<Array<SpinReward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpinRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpinRewards();
            return result;
        }
    }
    async getTotalScore(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalScore();
            return result;
        }
    }
    async getUserActivity(arg0: Principal): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserActivity(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVirtualPetHub(): Promise<VirtualPetHub | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVirtualPetHub();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVirtualPetHub();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isClaimedAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isClaimedAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isClaimedAdmin();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordActivity(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordActivity(arg0, arg1);
            return result;
        }
    }
    async recordSpinReward(arg0: SpinReward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSpinReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSpinReward(arg0);
            return result;
        }
    }
    async removeFriend(arg0: Principal): Promise<FriendResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async resetAdmin(): Promise<ResetResult> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAdmin();
                return from_candid_ResetResult_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAdmin();
            return from_candid_ResetResult_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerRewards(arg0: Reward): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerRewards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerRewards(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveVirtualPetHub(arg0: VirtualPetHub): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVirtualPetHub(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVirtualPetHub(arg0);
            return result;
        }
    }
    async sendChatMessage(arg0: Principal, arg1: string): Promise<ChatResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0, arg1);
                return from_candid_ChatResult_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0, arg1);
            return from_candid_ChatResult_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<FriendResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return from_candid_FriendResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async unbanModule(arg0: string): Promise<ModuleBanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanModule(arg0);
                return from_candid_ModuleBanResult_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanModule(arg0);
            return from_candid_ModuleBanResult_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePresence(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePresence();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePresence();
            return result;
        }
    }
}
function from_candid_AdminUserView_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserView): AdminUserView {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ChatResult_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatResult): ChatResult {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ClaimResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimResult): ClaimResult {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FriendResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendResult): FriendResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ModuleBanResult_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ModuleBanResult): ModuleBanResult {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ResetResult_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResetResult): ResetResult {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RewardResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardResult): RewardResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AvatarConfigRef]): AvatarConfigRef | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Reward]): Reward | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AvatarConfig]): AvatarConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VirtualPetHub]): VirtualPetHub | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    principal: Principal;
    name: string;
    lastSeen: bigint;
    avatarConfig: [] | [_AvatarConfigRef];
}): {
    status: string;
    principal: Principal;
    name: string;
    lastSeen: bigint;
    avatarConfig?: AvatarConfigRef;
} {
    return {
        status: value.status,
        principal: value.principal,
        name: value.name,
        lastSeen: value.lastSeen,
        avatarConfig: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.avatarConfig))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig: [] | [_AvatarConfig];
    accessibilitySettings: _AccessibilitySettings;
}): {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig?: AvatarConfig;
    accessibilitySettings: AccessibilitySettings;
} {
    return {
        age: value.age,
        mascotPreference: value.mascotPreference,
        theme: value.theme,
        approvedContacts: value.approvedContacts,
        parentPrincipal: value.parentPrincipal,
        name: value.name,
        screenTimeLimit: value.screenTimeLimit,
        avatarUrl: value.avatarUrl,
        contentFilterLevel: value.contentFilterLevel,
        avatarConfig: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.avatarConfig)),
        accessibilitySettings: value.accessibilitySettings
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n35(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    notFound: null;
} | {
    notAdmin: null;
}): RewardResult {
    return "sent" in value ? RewardResult.sent : "notFound" in value ? RewardResult.notFound : "notAdmin" in value ? RewardResult.notAdmin : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    banned: null;
} | {
    unbanned: null;
} | {
    notBanned: null;
} | {
    alreadyBanned: null;
}): ModuleBanResult {
    return "banned" in value ? ModuleBanResult.banned : "unbanned" in value ? ModuleBanResult.unbanned : "notBanned" in value ? ModuleBanResult.notBanned : "alreadyBanned" in value ? ModuleBanResult.alreadyBanned : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    claimed: null;
} | {
    alreadyClaimed: {
        admin: Principal;
    };
}): {
    __kind__: "claimed";
    claimed: null;
} | {
    __kind__: "alreadyClaimed";
    alreadyClaimed: {
        admin: Principal;
    };
} {
    return "claimed" in value ? {
        __kind__: "claimed",
        claimed: value.claimed
    } : "alreadyClaimed" in value ? {
        __kind__: "alreadyClaimed",
        alreadyClaimed: value.alreadyClaimed
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reset: null;
} | {
    noAdmin: null;
}): ResetResult {
    return "reset" in value ? ResetResult.reset : "noAdmin" in value ? ResetResult.noAdmin : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    banned: null;
} | {
    notFriends: null;
}): ChatResult {
    return "sent" in value ? ChatResult.sent : "banned" in value ? ChatResult.banned : "notFriends" in value ? ChatResult.notFriends : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyFriends: null;
} | {
    sent: null;
} | {
    alreadyRequested: null;
} | {
    notFound: null;
} | {
    selfRequest: null;
} | {
    accepted: null;
} | {
    declined: null;
} | {
    alreadyAccepted: null;
} | {
    removed: null;
}): FriendResult {
    return "alreadyFriends" in value ? FriendResult.alreadyFriends : "sent" in value ? FriendResult.sent : "alreadyRequested" in value ? FriendResult.alreadyRequested : "notFound" in value ? FriendResult.notFound : "selfRequest" in value ? FriendResult.selfRequest : "accepted" in value ? FriendResult.accepted : "declined" in value ? FriendResult.declined : "alreadyAccepted" in value ? FriendResult.alreadyAccepted : "removed" in value ? FriendResult.removed : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserView>): Array<AdminUserView> {
    return value.map((x)=>from_candid_AdminUserView_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n33(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig?: AvatarConfig;
    accessibilitySettings: AccessibilitySettings;
}): {
    age: bigint;
    mascotPreference: string;
    theme: string;
    approvedContacts: Array<Principal>;
    parentPrincipal: Principal;
    name: string;
    screenTimeLimit: bigint;
    avatarUrl: string;
    contentFilterLevel: string;
    avatarConfig: [] | [_AvatarConfig];
    accessibilitySettings: _AccessibilitySettings;
} {
    return {
        age: value.age,
        mascotPreference: value.mascotPreference,
        theme: value.theme,
        approvedContacts: value.approvedContacts,
        parentPrincipal: value.parentPrincipal,
        name: value.name,
        screenTimeLimit: value.screenTimeLimit,
        avatarUrl: value.avatarUrl,
        contentFilterLevel: value.contentFilterLevel,
        avatarConfig: value.avatarConfig ? candid_some(value.avatarConfig) : candid_none(),
        accessibilitySettings: value.accessibilitySettings
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
